### ISSUE TITLE
js api for the olapic widget?

### ISSUE THREAD

**Issue by z1haze** [Olapic/PublicDocs#6]
Hi, I am trying to move our existing website that uses olapic to a new js framework, which loads the data serverside, and renders the templates client side after the fact. So thing like this will not work.

```
<div id="olapic_specific_widget"></div>
                <script type="text/javascript"
                        src="https://photorankstatics-a.akamaihd.net/81b03e40475846d5883661ff57b34ece/static/frontend/latest/build.min.js"
                        data-olapic="olapic_specific_widget"
                        data-instance="somehash"
                        data-apikey="somekey"
                        :data-tags="product.reviewID"
                        async="async">
                </script>
```

I am looking for some sort of an api that I can load this script from after the dom has been loaded. I have been searching the web for a while now, but not able to find much useful information. We are on a demandware platform, but our setup is a little more advanced than the out of the box application, thus we need some sort of way to load this script and pass whatever parameters that are needed. Thank you.

**Comment by jhankim** [comment]
@z1haze Olapic offers SDK load method that will allow you to specifically invoke Olapic load events. Please see technical documentation here (requires Olapic admin access): https://olapic1.zendesk.com/hc/en-us/articles/203456360-SDK-Widget-Load-Method. 

Here a quick gist illustrating the SDK load method as reference: https://gist.github.com/jhankim/d39b12ec2bb55e68f84aa8257c57074e

**Comment by z1haze** [comment]
is the gist you provided the section that I need to replace the code I posted earlier?

**Comment by jhankim** [comment]
@z1haze Happy to help out further, this will need to follow our client support procedures so that our support and engineering team can dig in further. I would create a ticket for you directly, but I don't have your email address. Do you mind contacting support@olapic.com directly? Definitely want to avoid exchanging emails on public threads.

**Comment by z1haze** [comment]
I appreciate the response, I was able to get it all working after all. Didnt use the sdk. Used vanilla javascript to append a script tag to the dom and used setAttribute to pass all of the data-attributes in with it, and it executed just fine. Thanks though!

**Comment by jhankim** [comment]
@z1haze Glad you got it figured out! Feel free to reach out over email if you come across anything else.

**Comment by ShwetaRBhat** [comment]
@z1haze , Can you please give an example code for appending script tag to the dom and how did you use setAttribute in Vue.js? I am using react js and I need to use olapic script in react. Please help!

**Comment by z1haze** [comment]
Its been years since I did this, I dont even have access to the project anymore, but I imagine it was something like this:

```js
var my_awesome_script = document.createElement('script');

my_awesome_script.setAttribute('src','http://example.com/site.js');

document.head.appendChild(my_awesome_script);
```
